// lib/serviceData.core.ts  — Existing 6 services (enriched)

export const CORE_SERVICES = [
    {
        slug: 'seo-content-marketing',
        title: 'SEO & Content Marketing',
        iconEmoji: '🔍',
        metaDesc: 'Dominate Google, Bing and AI search results with proven on-page, off-page and technical SEO strategies combined with high-quality content that converts visitors into leads.',
        badgeClass: 'badge-blue',
        badge: 'Organic Growth',
        tagline: 'Turn your website into a 24/7 lead-generation machine with content that ranks and converts.',
        gradientFrom: '#3b82f6',
        gradientTo: '#1d4ed8',
        description: `Search Engine Optimisation (SEO) is the process of improving your website's visibility on search engines like Google and Bing so that potential customers find you before they find your competitors. It combines technical website health, keyword-targeted content, and authority-building through backlinks. At ScalerHouse, our SEO & Content Marketing service is a full-funnel growth engine — we don't just chase rankings, we optimise for revenue. Our content strategists research exactly what your buyers search at every stage of their journey and create articles, landing pages and resources that answer those questions compellingly. Over time, this builds compounding organic traffic that reduces your reliance on paid advertising.`,
        whyItMatters: [
            { icon: '📈', title: 'Compounding Returns', desc: 'Unlike paid ads that stop the moment you pause spend, SEO traffic grows and compounds over every month you invest.' },
            { icon: '🎯', title: 'Intent-Driven Leads', desc: 'Organic visitors are actively searching for your solution — they convert at 8× the rate of social or display traffic.' },
            { icon: '🏆', title: 'Brand Authority', desc: 'Consistently ranking at the top of Google builds trust and signals market leadership to both prospects and partners.' },
        ],
        howItWorks: [
            { step: '1', title: 'Technical SEO Audit', desc: 'We crawl every page of your site, identifying speed issues, broken links, crawl errors, duplicate content and Core Web Vitals gaps that suppress your rankings.' },
            { step: '2', title: 'Keyword & Market Research', desc: 'Our team maps 200–500 keywords across awareness, consideration and decision stages, prioritising by search volume, intent and realistic ranking opportunity.' },
            { step: '3', title: 'On-Page Optimisation', desc: 'We rewrite meta titles, descriptions, H-tags, internal linking and schema markup to signal exactly what each page is about to search engines.' },
            { step: '4', title: 'Content Creation', desc: 'Our SEO writers produce in-depth, E-E-A-T-compliant articles, pillar pages and landing pages that outrank and outperform competitor content.' },
            { step: '5', title: 'Link Building', desc: 'We secure high-authority backlinks through digital PR, guest posts, resource pages and HARO outreach — boosting domain rating and page authority.' },
            { step: '6', title: 'Reporting & Iteration', desc: 'Monthly SEO dashboards track keyword movements, organic traffic, leads and revenue attribution — fuelling continuous strategy improvements.' },
        ],
        smallBizBenefits: [
            'Appear in local and national searches with limited budget',
            'Build lasting brand visibility without ongoing ad spend',
            'Generate qualified enquiries from buyers ready to act',
            'Compete with larger brands using content and authority',
        ],
        enterpriseBenefits: [
            'Enterprise-grade technical SEO — site migrations, hreflang, log file analysis',
            'Content programmes at scale — 30–100+ articles per month',
            'Multi-regional and multilingual SEO strategies',
            'Advanced competitive moat-building through topical authority',
        ],
        process: [
            { icon: '🔎', label: 'Site Audit', desc: 'Deep technical analysis of 200+ ranking factors.' },
            { icon: '📋', label: 'Strategy', desc: 'Keyword maps, content briefs and a 12-month roadmap.' },
            { icon: '✍️', label: 'Content', desc: 'E-E-A-T rich articles, guides and landing pages written by experts.' },
            { icon: '⚙️', label: 'On-Page', desc: 'Meta tags, schema markup, internal linking and page speed fixes.' },
            { icon: '🔗', label: 'Link Building', desc: 'White-hat authority backlinks from relevant, high-DA domains.' },
            { icon: '📊', label: 'Reporting', desc: 'Monthly ranking, traffic and revenue reports with action plans.' },
        ],
        faqs: [
            { q: 'How long does SEO take to show results?', a: 'Most clients see measurable ranking improvements within 60–90 days and significant traffic growth by month 4–6. Highly competitive industries may take 9–12 months to reach page-one dominance.' },
            { q: 'Do you guarantee #1 rankings on Google?', a: 'No ethical agency can guarantee specific rankings — anyone who does is misleading you. We guarantee a documented strategy, consistent execution and transparent reporting tied to traffic and lead growth.' },
            { q: 'What is E-E-A-T and why does it matter?', a: 'E-E-A-T stands for Experience, Expertise, Authoritativeness and Trustworthiness — Google\'s quality rater guidelines. Content that demonstrates real expertise ranks higher and converts better. Every piece we create is written by subject-matter experts.' },
            { q: 'Do you do local SEO?', a: 'Yes. Local SEO includes optimising your Google Business Profile, building local citations, earning local backlinks and creating location-specific landing pages to dominate map-pack and near-me searches.' },
            { q: 'How many keywords will you target?', a: 'Our keyword research typically identifies 200–500 relevant keywords. We prioritise them into a tiered roadmap — starting with high-intent, lower-competition terms for early wins before building to highly competitive head terms.' },
            { q: 'Will you write the content or do I need to?', a: 'We handle everything — research, brief writing, expert-level content creation, editing and publishing. You simply review and approve before anything goes live.' },
            { q: 'How do you build backlinks?', a: 'We use white-hat techniques only: digital PR, journalist outreach via HARO, resource page link building, guest posting on relevant industry publications and broken-link reclamation.' },
            { q: 'Can SEO work alongside paid ads?', a: 'Absolutely — they complement each other. Paid ads deliver instant traffic while SEO builds long-term compounding growth. Sharing keyword data between channels improves performance on both.' },
        ],
    },
    {
        slug: 'performance-ads',
        title: 'Performance Ads',
        iconEmoji: '📣',
        metaDesc: 'Maximise ROI with data-driven Google, Meta, LinkedIn and TikTok advertising campaigns engineered to acquire customers profitably at scale.',
        badgeClass: 'badge-cyan',
        badge: 'Paid Growth',
        tagline: 'Reach your ideal customers the moment they are ready to buy and scale your revenue predictably.',
        gradientFrom: '#06b6d4',
        gradientTo: '#0891b2',
        description: `Performance advertising is the discipline of running paid digital campaigns on platforms like Google Ads, Meta Ads, LinkedIn and TikTok where every rupee of spend is tracked to a measurable outcome — clicks, leads, purchases or revenue. Unlike traditional advertising, performance ads give you real-time data on what is working, allow instant budget reallocation and can be scaled up or down on demand. ScalerHouse manages the full stack: creative strategy, audience research, campaign architecture, bid management and continuous optimisation. We treat your ad account as a profit centre — our goal is always to improve your Return on Ad Spend (ROAS) and lower your Cost Per Acquisition (CPA) month over month.`,
        whyItMatters: [
            { icon: '⚡', title: 'Instant Traffic', desc: 'Unlike SEO, performance ads can drive targeted visitors to your site within hours of launch — ideal for launches, promotions and fast growth.' },
            { icon: '🎯', title: 'Laser Targeting', desc: 'Reach the exact audience by demographics, interests, job title, search intent and even competitor website visitors — no wasted spend.' },
            { icon: '📉', title: 'Measurable ROI', desc: 'Every click, lead and sale is attributed to the exact ad creative, audience and keyword — so you always know what\'s generating revenue.' },
        ],
        howItWorks: [
            { step: '1', title: 'Audience & Market Research', desc: 'We analyse your target customers, study competitor ad strategies and identify the highest-value audiences across each platform.' },
            { step: '2', title: 'Campaign Architecture', desc: 'We build a structured campaign framework — campaigns, ad sets, audiences and bidding strategies — optimised for your specific KPIs.' },
            { step: '3', title: 'Creative Development', desc: 'Our team produces scroll-stopping ad creatives: copy, static images, carousels and short-form video ads tested against each audience.' },
            { step: '4', title: 'Launch & Tracking', desc: 'We implement pixel tracking, conversion APIs and UTM parameters to ensure every conversion is accurately attributed before going live.' },
            { step: '5', title: 'Optimisation & Testing', desc: 'We run continuous A/B tests on creatives, audiences and landing pages, pausing losers and scaling winners to improve ROAS weekly.' },
            { step: '6', title: 'Scaling & Reporting', desc: 'As campaigns prove profitability, we systematically scale budgets while maintaining CPA targets, and deliver weekly performance reports.' },
        ],
        smallBizBenefits: [
            'Drive immediate, qualified traffic with flexible budgets from ₹15,000/month',
            'Target hyperlocal audiences — city, pincode or radius-based',
            'Full creative production included — no agency fees for design',
            'Transparent weekly reporting so you see exactly where every rupee goes',
        ],
        enterpriseBenefits: [
            'Multi-platform campaigns spanning Google, Meta, LinkedIn and programmatic DSPs',
            'Advanced attribution modelling — data-driven, MTA and custom models',
            'Dedicated account team with a senior media buyer and creative strategist',
            'Account-based marketing (ABM) campaigns for B2B enterprise pipelines',
        ],
        process: [
            { icon: '🔍', label: 'Research', desc: 'Audience profiling, competitor ad audits and opportunity mapping.' },
            { icon: '🏗️', label: 'Build', desc: 'Campaign architecture, tracking setup and creative production.' },
            { icon: '🚀', label: 'Launch', desc: 'Precision campaign launch with full conversion tracking live.' },
            { icon: '🧪', label: 'Test', desc: 'Continuous A/B testing of creatives, audiences and landing pages.' },
            { icon: '📈', label: 'Optimise', desc: 'Daily bid adjustments and weekly budget reallocation to top performers.' },
            { icon: '📋', label: 'Report', desc: 'Weekly dashboards with ROAS, CPA, impressions, clicks and conversion data.' },
        ],
        faqs: [
            { q: 'What platforms do you run ads on?', a: 'We manage campaigns on Google Search & Display, YouTube, Meta (Facebook & Instagram), LinkedIn Ads and TikTok Ads. Platform selection depends on your audience and goals.' },
            { q: 'What is the minimum ad budget you recommend?', a: 'We recommend a minimum of ₹30,000/month in ad spend for meaningful data. Smaller budgets restrict the algorithm\'s ability to optimise. Our management fee is separate from ad spend.' },
            { q: 'How long before I see results from paid ads?', a: 'Simple search campaigns can generate leads within 48–72 hours of launch. Full optimisation and learning phase for a new account typically takes 4–6 weeks before performance stabilises.' },
            { q: 'Do you create ad creatives or do I need to provide them?', a: 'We include full creative production — copywriting, graphic design and video editing. You provide brand assets (logo, fonts, brand guidelines) and we handle everything else.' },
            { q: 'What is ROAS and how do you improve it?', a: 'ROAS (Return on Ad Spend) is revenue generated per rupee spent. We improve it by eliminating wasted spend on low-performing keywords and audiences, improving landing page conversion rates and scaling proven creative angles.' },
            { q: 'Can you take over an existing ad account?', a: 'Absolutely. We begin with a thorough audit of your historical data, identifying waste and opportunities before making structured changes to protect existing performance.' },
            { q: 'Do you work on a percentage of ad spend or a flat fee?', a: 'We offer both structures. Most clients prefer a hybrid model — a flat management retainer plus a small percentage of ad spend above a threshold. We\'ll recommend the right model for your budget.' },
            { q: 'How do you track conversions accurately?', a: 'We implement Google\'s enhanced conversions, Meta\'s Conversions API and server-side tracking via GTM to ensure accurate attribution even with iOS privacy restrictions and ad blockers.' },
        ],
    },
    {
        slug: 'social-media-management',
        title: 'Social Media Management',
        iconEmoji: '📱',
        metaDesc: 'Build a loyal brand community, grow your following and drive real business results with strategic social media management across Instagram, LinkedIn, Facebook and more.',
        badgeClass: 'badge-purple',
        badge: 'Brand Building',
        tagline: 'Connect, inspire and convert — consistently — across every social platform your audience lives on.',
        gradientFrom: '#a855f7',
        gradientTo: '#7e22ce',
        description: `Social media management is the ongoing process of creating, scheduling, publishing and monitoring content across social platforms like Instagram, LinkedIn, Facebook, YouTube Shorts and X (Twitter) to build brand awareness, foster community and generate business enquiries. Done well, it elevates a brand from anonymous to authoritative and transforms followers into loyal customers. ScalerHouse manages end-to-end social media — from monthly content calendars and professional visual design to daily community engagement and monthly analytics reviews. Our strategies are rooted in platform algorithms, audience psychology and your commercial goals, so every post serves a purpose beyond filling a feed.`,
        whyItMatters: [
            { icon: '📣', title: 'Brand Awareness at Scale', desc: 'Billions of people open social apps daily — a consistent, high-quality presence puts your brand in front of potential customers who are not yet searching for you.' },
            { icon: '💬', title: 'Two-Way Trust Building', desc: 'Social media allows you to have real conversations with your audience — answering questions, showing behind-the-scenes moments and humanising your brand builds trust that no ad can buy.' },
            { icon: '🛍️', title: 'Social Commerce', desc: 'Instagram Shopping, LinkedIn lead gen forms and Facebook Shops turn your social profiles into revenue channels that drive direct sales and enquiries.' },
        ],
        howItWorks: [
            { step: '1', title: 'Brand & Audience Audit', desc: 'We analyse your current social presence, benchmark against competitors and define your ideal audience personas for each platform.' },
            { step: '2', title: 'Platform & Content Strategy', desc: 'We develop a platform-specific strategy — deciding content formats, posting frequency, brand voice and content pillars aligned with your business goals.' },
            { step: '3', title: 'Monthly Content Calendar', desc: 'A detailed, pre-approved content calendar is produced 2 weeks ahead, covering static posts, reels, carousels, stories and interactive content.' },
            { step: '4', title: 'Design & Production', desc: 'Our in-house designers create on-brand graphics, reels and carousels while copywriters craft engaging captions with strategic hashtags and CTAs.' },
            { step: '5', title: 'Publishing & Community Management', desc: 'We schedule posts at optimal times, monitor all comments and DMs and engage with your community — so your accounts feel alive and responsive 7 days a week.' },
            { step: '6', title: 'Analytics & Strategy Review', desc: 'Monthly reports cover reach, engagement, follower growth, story views and leads — with clear insights on what worked and what evolves next month.' },
        ],
        smallBizBenefits: [
            'Save 30+ hours per month — we handle all content creation and posting',
            'Professional, consistent brand image even on a small business budget',
            'Grow a genuine local and national following organically',
            'Convert social followers into customers with strategic CTAs',
        ],
        enterpriseBenefits: [
            'Omnichannel brand voice alignment across 5+ platforms and regional markets',
            'Influencer identification, negotiation and campaign management',
            'Social listening and competitor monitoring at enterprise scale',
            'Crisis communication protocols and real-time response management',
        ],
        process: [
            { icon: '🎯', label: 'Strategy', desc: 'Audience research, competitor analysis and platform-specific content strategy.' },
            { icon: '📅', label: 'Planning', desc: 'Monthly content calendar approved by you 2 weeks in advance.' },
            { icon: '🎨', label: 'Design', desc: 'On-brand graphics, reels, carousels and stories by professional designers.' },
            { icon: '✍️', label: 'Copywriting', desc: 'Engaging captions, hashtag research and platform-native copy.' },
            { icon: '📲', label: 'Publishing', desc: 'Scheduled posts at peak engagement times across all platforms.' },
            { icon: '💬', label: 'Engagement', desc: 'Community management — replying to comments, DMs and brand mentions daily.' },
        ],
        faqs: [
            { q: 'Which social media platforms do you manage?', a: 'We manage Instagram, Facebook, LinkedIn, X (Twitter), YouTube Shorts and Pinterest. The platforms we prioritise are determined by where your audience spends time, not what\'s popular.' },
            { q: 'How many posts per week will you create?', a: 'Posting frequency is defined in your package — typically 5–7 posts per week across platforms. This includes a mix of static posts, carousels, stories and short-form video (reels).' },
            { q: 'Do you handle reels and video content?', a: 'Yes. All our packages include short-form video production — we script, edit and caption reels and YouTube Shorts. For higher-tier packages, we also produce long-form video content.' },
            { q: 'Will I review content before it is posted?', a: 'Absolutely. We share the monthly content calendar and all creatives for your approval before anything goes live. You can request changes at any time within the revision policy.' },
            { q: 'How do you handle negative comments or trolls?', a: 'We have a clear community management protocol — responding to genuine criticism with empathy and professionalism and flagging sensitive issues to you immediately for guidance. Spam and abusive comments are managed per your brand guidelines.' },
            { q: 'Can you grow my followers quickly?', a: 'We grow followers sustainably through great content, targeted hashtags, engagement strategies and — if budgeted — paid follower campaigns. We do not use bots, follow/unfollow tactics or any method that violates platform terms.' },
            { q: 'Do you work with influencers?', a: 'Yes — influencer identification, outreach, contract management and campaign tracking are available as an add-on or in our Premium packages. We work with nano, micro and macro influencers across categories.' },
            { q: 'What metrics do you report on?', a: 'We report on follower growth, post reach, impressions, engagement rate, story views, link clicks, profile visits and leads/enquiries generated — all in a branded monthly report.' },
        ],
    },
    {
        slug: 'web-design-development',
        title: 'Web Design & Development',
        iconEmoji: '💻',
        metaDesc: 'Get a stunning, conversion-optimised website built on modern technology — designed to rank on Google, load in under 2 seconds and turn visitors into paying customers.',
        badgeClass: 'badge-green',
        badge: 'Digital Storefront',
        tagline: 'Your website is your best salesperson — we build it to convert 24 hours a day, 7 days a week.',
        gradientFrom: '#22c55e',
        gradientTo: '#16a34a',
        description: `Web design and development is the process of planning, designing and building a website that represents your brand powerfully, ranks on search engines and converts visitors into customers or enquiries. A great website is not just visually impressive — it loads fast, works flawlessly on mobile, guides users intuitively towards a desired action and is built on clean, scalable code. ScalerHouse designs and builds websites from scratch — no drag-and-drop page builders, no bloated themes. We use modern frameworks like Next.js and React to deliver pixel-perfect, blazing-fast websites that score 90+ on Google PageSpeed and are architecturally ready to scale with your business.`,
        whyItMatters: [
            { icon: '🖥️', title: 'First Impressions Count', desc: 'Users form an opinion about your website in 0.05 seconds. A professional, modern design immediately signals credibility and makes prospects 75% more likely to trust your business.' },
            { icon: '📱', title: 'Mobile-First World', desc: 'Over 60% of web traffic is mobile. A site that looks great and loads fast on smartphones isn\'t optional — it\'s the baseline expectation for winning customers.' },
            { icon: '⚡', title: 'Speed = Revenue', desc: 'A 1-second delay in page load reduces conversions by 7%. Our performance-first builds ensure your site is never losing revenue to slow load times.' },
        ],
        howItWorks: [
            { step: '1', title: 'Discovery & UX Research', desc: 'We begin with deep-dive sessions to understand your business, audience and goals — mapping the ideal user journey from landing to conversion.' },
            { step: '2', title: 'Wireframing & Information Architecture', desc: 'We create low-fidelity wireframes for every key page, establishing clear content hierarchy, navigation flow and call-to-action placement before touching visuals.' },
            { step: '3', title: 'UI Design & Prototyping', desc: 'Our designers build high-fidelity mockups in Figma — covering desktop, tablet and mobile breakpoints — with your brand colours, typography and photography.' },
            { step: '4', title: 'Development', desc: 'We code the website in modern frameworks (Next.js, React, or WordPress/Webflow) following clean-code standards, accessibility guidelines and SEO best practices from the ground up.' },
            { step: '5', title: 'QA & Performance Testing', desc: 'Every page is rigorously tested across browsers and devices, with PageSpeed scores validated and all forms, integrations and CTAs confirmed working.' },
            { step: '6', title: 'Launch & Handover', desc: 'We handle DNS, hosting setup and final deployment. You receive a trained CMS walkthrough so you can manage content independently, plus 30 days of post-launch support.' },
        ],
        smallBizBenefits: [
            'Professional, modern website that builds instant credibility with prospects',
            'Mobile-first, responsive design that works on every device',
            'Easy-to-manage CMS so you can update content without a developer',
            'Built-in lead capture forms, WhatsApp integration and booking systems',
        ],
        enterpriseBenefits: [
            'Custom web applications, portals and dashboards on enterprise-grade infrastructure',
            'Complex third-party API integrations — CRM, ERP, payment gateways and more',
            'Multi-language, multi-region website architecture with localisation support',
            'Dedicated development team for ongoing feature development and maintenance',
        ],
        process: [
            { icon: '🔍', label: 'Discovery', desc: 'Business goals, user personas and competitor benchmarking.' },
            { icon: '📐', label: 'Wireframes', desc: 'Low-fidelity layouts defining structure before aesthetics.' },
            { icon: '🎨', label: 'UI Design', desc: 'Full visual designs in Figma across all screen sizes.' },
            { icon: '👨‍💻', label: 'Development', desc: 'Clean, fast and accessible code — no page builders.' },
            { icon: '🧪', label: 'QA Testing', desc: 'Cross-browser, cross-device and performance testing.' },
            { icon: '🚀', label: 'Launch', desc: 'Deployment, DNS setup, tracking install and post-launch support.' },
        ],
        faqs: [
            { q: 'How long does it take to build a website?', a: 'A standard 5–10 page business website takes 4–6 weeks. Larger sites, e-commerce platforms or custom web applications typically take 8–16 weeks depending on complexity.' },
            { q: 'Do you use templates or build custom designs?', a: 'Everything we build is custom-designed from scratch in Figma — tailored to your brand identity. We do not use pre-made templates or page builder themes.' },
            { q: 'Will my website be mobile-friendly?', a: 'Yes — every website we design is mobile-first by default, meaning we design for mobile screens before desktop. Every layout is tested on iOS, Android and all major browsers.' },
            { q: 'Will I be able to update the website myself?', a: 'Absolutely. We build on user-friendly CMS platforms (WordPress, Sanity, or a custom admin panel) and include a full CMS training session so your team can update text, images and pages without any coding knowledge.' },
            { q: 'Do you provide hosting?', a: 'We can recommend and set up hosting on fast, secure platforms like Vercel, AWS or WP Engine — or deploy to your existing hosting provider. Hosting costs are separate from our development fee.' },
            { q: 'Is SEO included in the website build?', a: 'Yes — all our websites are built with technical SEO foundations: clean URL structures, schema markup, fast page speeds, XML sitemaps, canonical tags and meta tag frameworks ready for your content team.' },
            { q: 'What happens after the website is launched?', a: 'We provide 30 days of free post-launch support for bug fixes and minor adjustments. After that, we offer monthly maintenance retainers covering security updates, plugin management, performance monitoring and ongoing changes.' },
            { q: 'Can you redesign my existing website?', a: 'Yes — a website redesign follows the same process as a new build. We audit your existing site for SEO value, ensuring no rankings or traffic are lost during the transition through proper redirects and content migration.' },
        ],
    },
    {
        slug: 'analytics-cro',
        title: 'Analytics & CRO',
        iconEmoji: '📊',
        metaDesc: 'Stop guessing and start growing — our data analytics and conversion rate optimisation service turns your website data into a clear roadmap for more leads and revenue.',
        badgeClass: 'badge-orange',
        badge: 'Optimisation',
        tagline: 'More traffic is not always the answer. Getting more from your existing visitors is.',
        gradientFrom: '#f97316',
        gradientTo: '#ea580c',
        description: `Analytics and Conversion Rate Optimisation (CRO) is the practice of using data to understand how visitors behave on your website and systematically testing improvements to increase the percentage who complete a desired action — filling a form, making a purchase or booking a call. While most businesses focus on driving more traffic, CRO focuses on making every visitor count. ScalerHouse sets up enterprise-grade tracking across your entire digital ecosystem — website, ads, email and social — and then identifies where users drop off, hesitate or get confused. We formulate hypotheses based on data and psychological principles, then A/B test solutions until we find what works — permanently improving your conversion rates and revenue without increasing your ad spend.`,
        whyItMatters: [
            { icon: '💰', title: 'More Revenue Without More Spend', desc: 'Improving a 2% conversion rate to 4% doubles your revenue from the same traffic — CRO is the highest-leverage investment in your digital ecosystem.' },
            { icon: '🔍', title: 'Understand Your Customers', desc: 'Heatmaps, session recordings and funnel analysis reveal exactly what your real customers want and where they get frustrated — intelligence you can apply across all marketing channels.' },
            { icon: '📉', title: 'Reduce Cost Per Acquisition', desc: 'When more of your paid traffic converts, your effective CPA drops — making every ad campaign more profitable without changing your budget.' },
        ],
        howItWorks: [
            { step: '1', title: 'Tracking Audit & Setup', desc: 'We implement or fix GA4, Google Tag Manager, Meta Pixel and server-side tracking to ensure every user action is captured accurately before any analysis begins.' },
            { step: '2', title: 'Data Analysis & Funnel Mapping', desc: 'We build conversion funnels, set up event tracking and analyse behavioural data to identify drop-off points, underperforming pages and revenue gaps.' },
            { step: '3', title: 'Qualitative Research', desc: 'Heatmaps, scroll maps, session recordings and on-site surveys reveal the human story behind the numbers — showing us what is confusing or frustrating real visitors.' },
            { step: '4', title: 'Hypothesis Development', desc: 'Based on data and conversion psychology, we formulate prioritised hypotheses for what changes will most improve conversion rate, scored by potential impact and effort.' },
            { step: '5', title: 'A/B Testing', desc: 'We design and run statistically valid A/B or multivariate tests using Google Optimize or VWO — testing headlines, CTAs, layouts, forms and page flow.' },
            { step: '6', title: 'Implementation & Continuous Improvement', desc: 'Winning variants are implemented permanently, and we start the next test — creating a continuous cycle of improvement that compounds gains month over month.' },
        ],
        smallBizBenefits: [
            'Understand exactly where your website is losing enquiries and revenue',
            'Get more customers from your existing traffic without increasing ad spend',
            'Clear, jargon-free reports connecting website performance to your bottom line',
            'Google Analytics 4 and Tag Manager correctly configured from day one',
        ],
        enterpriseBenefits: [
            'Advanced multi-touch attribution modelling across complex buyer journeys',
            'Personalisation engines delivering dynamic content to different audience segments',
            'Predictive analytics and machine-learning models for churn and LTV forecasting',
            'Full data stack management — BigQuery, Looker Studio and custom dashboards',
        ],
        process: [
            { icon: '🧩', label: 'Audit', desc: 'Tracking audit to ensure clean, complete data collection.' },
            { icon: '📊', label: 'Analysis', desc: 'Funnel analysis, event tracking and behavioural reporting.' },
            { icon: '🎥', label: 'Research', desc: 'Heatmaps, session recordings and user surveys.' },
            { icon: '💡', label: 'Hypotheses', desc: 'Data-backed test ideas ranked by expected impact.' },
            { icon: '🧪', label: 'A/B Tests', desc: 'Statistically valid experiments on key conversion points.' },
            { icon: '🔁', label: 'Iterate', desc: 'Winners go live, new tests begin — compounding gains every cycle.' },
        ],
        faqs: [
            { q: 'What is Conversion Rate Optimisation (CRO)?', a: 'CRO is the process of increasing the percentage of your website visitors who take a desired action — enquiring, purchasing or signing up — through data analysis and structured experimentation. The goal is more revenue from your existing traffic.' },
            { q: 'How long does a typical A/B test run?', a: 'Most A/B tests need to run for 2–4 weeks to reach statistical significance (95%+ confidence). Running tests too short risks making decisions based on random fluctuations rather than real data.' },
            { q: 'What tools do you use for CRO?', a: 'We use Google Analytics 4, Google Tag Manager, Hotjar (heatmaps & recordings), VWO or Google Optimize for A/B testing, and Looker Studio for custom reporting dashboards.' },
            { q: 'Can CRO work for e-commerce sites?', a: 'CRO is particularly high-impact for e-commerce — improving product pages, checkout flows, cart abandonment recovery and upsell sequences can dramatically increase revenue without additional traffic cost.' },
            { q: 'What kind of conversion improvements can I realistically expect?', a: 'Results vary by industry and starting point. Our average client sees a 25–60% improvement in conversion rate within 3–6 months of consistent testing. The gains compound over time as each winning test builds on the last.' },
            { q: 'Do I need a lot of traffic for CRO to work?', a: 'A/B testing requires sufficient traffic to reach statistical significance — generally 500–1,000 conversions per variant per month. For lower-traffic sites, we focus on qualitative research and best-practice page improvements first.' },
            { q: 'Will you also improve our analytics reporting?', a: 'Yes — clean, actionable data is the foundation of everything we do. We build custom GA4 dashboards and Looker Studio reports that show you exactly what matters: traffic, leads, revenue and return on investment by channel.' },
            { q: 'Is analytics setup a one-time project or ongoing?', a: 'The initial tracking setup is a one-time project. Ongoing CRO — running tests, analysing results and iterating — is best as a monthly retainer since the gains compound continuously over time.' },
        ],
    },
    {
        slug: 'email-marketing',
        title: 'Email Marketing & Automation',
        iconEmoji: '✉️',
        metaDesc: 'Nurture leads, drive repeat sales and build lasting customer relationships with strategic email marketing campaigns and intelligent automation flows.',
        badgeClass: 'badge-pink',
        badge: 'Retention',
        tagline: 'The highest-ROI digital channel — ₹42 returned for every ₹1 spent — is waiting to work for your brand.',
        gradientFrom: '#ec4899',
        gradientTo: '#db2777',
        description: `Email marketing is the practice of sending targeted, personalised email campaigns to your audience — prospects, leads and existing customers — to nurture relationships, drive sales and increase lifetime value. With an average ROI of 4,200%, email consistently outperforms every other digital channel. ScalerHouse manages email marketing end-to-end: strategy, segmentation, copywriting, design, automation setup and deliverability management. We build automated flows that run 24/7 — welcoming new subscribers, recovering abandoned carts, re-engaging dormant customers and upselling at the perfect moment — turning your email list into a reliable, always-on revenue channel.`,
        whyItMatters: [
            { icon: '💎', title: 'Highest ROI Channel', desc: 'Email marketing delivers an average return of ₹42 for every ₹1 spent — outperforming paid social, SEO and display advertising on a pure ROI basis.' },
            { icon: '🔒', title: 'You Own the Channel', desc: 'Unlike social media where algorithms control reach, your email list is a first-party asset you own completely — algorithm changes cannot take it away.' },
            { icon: '🤖', title: 'Revenue While You Sleep', desc: 'Automated sequences — welcome series, cart abandonment, post-purchase flows — run 24/7 generating revenue without any manual intervention.' },
        ],
        howItWorks: [
            { step: '1', title: 'Email Audit & List Health', desc: 'We audit your existing email platform, list quality, deliverability reputation and automation flows — identifying what to fix before building anything new.' },
            { step: '2', title: 'Strategy & Segmentation', desc: 'We define your email programme strategy — audience segments, content pillars, frequency and the automated flows that will drive the highest ROI for your business.' },
            { step: '3', title: 'Automation Build', desc: 'We set up core automation flows: welcome series, lead nurture drips, cart/form abandonment recovery, post-purchase onboarding and re-engagement campaigns.' },
            { step: '4', title: 'Template Design', desc: 'Our designers create branded, mobile-optimised email templates that render perfectly across all clients — Gmail, Outlook, Apple Mail and mobile apps.' },
            { step: '5', title: 'Campaign Management', desc: 'We plan, write, design and send regular campaigns — newsletters, product launches, promotions and event announcements — on your behalf every month.' },
            { step: '6', title: 'Analytics & Optimisation', desc: 'Monthly reports track open rates, click rates, revenue per email and list growth — with continuous A/B testing of subject lines, CTAs and send times.' },
        ],
        smallBizBenefits: [
            'Turn your email list into a direct revenue channel without ongoing ad spend',
            'Automated welcome sequences that convert new subscribers into first-time buyers',
            'Monthly newsletters that keep your brand top-of-mind with past customers',
            'Re-engagement campaigns that recover dormant subscribers and lost revenue',
        ],
        enterpriseBenefits: [
            'Advanced behavioural segmentation — lifecycle stage, purchase history and predictive LTV',
            'Complex multi-step automation journeys across 30–90 touchpoints',
            'Deliverability management: dedicated IPs, domain warming, spam score monitoring',
            'Integration with CRM, e-commerce platforms and customer data platforms (CDPs)',
        ],
        process: [
            { icon: '🔍', label: 'Audit', desc: 'Platform review, list health check and deliverability assessment.' },
            { icon: '🗺️', label: 'Strategy', desc: 'Segmentation, flow mapping and content calendar planning.' },
            { icon: '⚙️', label: 'Automation', desc: 'Core flow builds — welcome, nurture, abandonment and re-engagement.' },
            { icon: '🎨', label: 'Design', desc: 'Mobile-first email templates aligned to your brand identity.' },
            { icon: '✍️', label: 'Copywriting', desc: 'High-converting subject lines, preview text and email body copy.' },
            { icon: '📈', label: 'Optimise', desc: 'A/B testing, deliverability monitoring and monthly performance reviews.' },
        ],
        faqs: [
            { q: 'Which email platforms do you work with?', a: 'We work with Klaviyo, Mailchimp, ActiveCampaign, HubSpot, Brevo (Sendinblue) and most major ESPs. We\'ll recommend the best platform for your business size, e-commerce vs B2B needs and budget.' },
            { q: 'How often should we email our list?', a: 'For most brands, 2–4 emails per month strikes the right balance between staying top-of-mind and avoiding unsubscribe surges. E-commerce brands with strong promotional calendars often benefit from weekly sends during peak seasons.' },
            { q: 'What are email automation flows and why do I need them?', a: 'Automation flows are pre-built email sequences triggered by specific actions — subscribing, abandoning a cart, making a purchase or going dormant. They run 24/7 without manual effort and are the highest-ROI part of any email programme.' },
            { q: 'My open rates are very low. Can you fix that?', a: 'Low open rates usually result from poor subject lines, list hygiene issues or deliverability problems (landing in spam). We audit and fix all three — cleaning your list, warming the sender domain and writing subject lines that get opened.' },
            { q: 'Is my email list compliant with GDPR and DPDP?', a: 'Compliance is critical. We audit your opt-in processes, unsubscribe flows and data retention policies to ensure full compliance with GDPR (Europe) and India\'s Digital Personal Data Protection Act.' },
            { q: 'Can you grow my email list as well?', a: 'Yes — list growth is part of our email strategy. We design opt-in forms, pop-ups, lead magnets and landing pages that convert website visitors into subscribers, integrated with your email platform.' },
            { q: 'How do you measure email marketing success?', a: 'Key metrics include open rate, click-through rate, conversion rate, revenue generated per email, list growth rate and unsubscribe rate. We track revenue attribution using UTM parameters and ESP revenue reporting.' },
            { q: 'What is email deliverability and how do you improve it?', a: 'Deliverability is whether your emails land in the inbox or spam folder. We improve it by authenticating your domain (SPF, DKIM, DMARC), cleaning inactive subscribers, warming new IPs and maintaining healthy sender reputation scores.' },
        ],
    },
];
