// lib/serviceData.new.ts  — 7 new services

export const NEW_SERVICES = [
    {
        slug: 'google-my-business',
        title: 'Google My Business Optimisation',
        iconEmoji: '📍',
        metaDesc: 'Dominate local search and Google Maps with professional GMB creation, optimisation and management so nearby customers choose you over competitors.',
        badgeClass: 'badge-blue',
        badge: 'Local SEO',
        tagline: 'Get found by customers near you — on Google Maps, local search and Google AI Overviews.',
        gradientFrom: '#4285f4',
        gradientTo: '#0f5bdb',
        description: `Google My Business (now called Google Business Profile) is your free business listing on Google that appears in Maps, local search results and the "Local Pack" — the 3 businesses shown above organic results when someone searches for a service near them. A fully optimised GMB profile is the single most powerful tool for any local or service-area business: 76% of people who search locally on their phone visit a business within 24 hours. ScalerHouse creates, verifies and optimises your Google Business Profile from the ground up — writing keyword-rich descriptions, adding services and products, uploading professional photos, setting up Q&A and managing your review strategy. We then monitor and update your profile monthly so Google's algorithm always sees it as active, relevant and trustworthy.`,
        whyItMatters: [
            { icon: '🗺️', title: 'Win the Local Pack', desc: 'Appearing in the top 3 of Google Maps results for your service drives more clicks than all organic results below it combined.' },
            { icon: '⭐', title: 'Reviews = Revenue', desc: 'Businesses with 4.5★+ and 100+ reviews receive 270% more web visits. We build a proactive review generation and response system that grows your rating.' },
            { icon: '📞', title: 'Direct Customer Actions', desc: 'GMB drives direct calls, directions, website visits and messages — tracking these actions as conversions gives you ROI-proof of local digital presence.' },
        ],
        howItWorks: [
            { step: '1', title: 'Profile Creation & Verification', desc: 'We create or claim your Google Business Profile, select the most relevant primary and secondary categories, and guide you through the Google verification process.' },
            { step: '2', title: 'Profile Optimisation', desc: 'We write a keyword-rich business description, complete all 100+ profile fields, add services/products with pricing and set up your Questions & Answers section.' },
            { step: '3', title: 'Photo & Visual Setup', desc: 'We upload a curated set of professional photos — exterior, interior, team, products and logo — following Google\'s image guidelines to maximise profile engagement.' },
            { step: '4', title: 'Review Generation Strategy', desc: 'We create a systematic review request process — email templates, WhatsApp follow-ups and QR codes — to generate a consistent flow of 5-star reviews from happy customers.' },
            { step: '5', title: 'GMB Post Management', desc: 'We publish weekly Google Posts — offers, events, updates and new services — signalling to Google that your profile is active and boosting local ranking.' },
            { step: '6', title: 'Monthly Monitoring & Reporting', desc: 'We track profile views, direction requests, calls and website clicks month-over-month — responding to reviews and Q&As and reporting on local search visibility improvements.' },
        ],
        smallBizBenefits: [
            'Appear in Google Maps when local customers search for your service',
            'Generate more phone calls and direction requests from nearby buyers',
            'Build a 4.5★+ review profile that instantly builds trust with new customers',
            'Beat larger competitors who have neglected their local presence',
        ],
        enterpriseBenefits: [
            'Multi-location GMB management — 10 to 1,000+ profiles managed centrally',
            'Google\'s Business API integration for bulk updates across all locations',
            'Reputation management at scale — monitoring and responding to all reviews',
            'Local SEO reporting dashboards showing ranking, traffic and call data per location',
        ],
        process: [
            { icon: '📋', label: 'Claim & Verify', desc: 'Profile creation, category selection and Google verification.' },
            { icon: '✍️', label: 'Optimise', desc: 'Keyword-rich descriptions, services, products and Q&A.' },
            { icon: '📸', label: 'Photography', desc: 'Upload 25+ professional photos across all categories.' },
            { icon: '⭐', label: 'Reviews', desc: 'Systematic review generation strategy and response templates.' },
            { icon: '📰', label: 'GMB Posts', desc: 'Weekly posts — offers, events and updates to signal activity.' },
            { icon: '📊', label: 'Reporting', desc: 'Monthly visibility, calls, clicks and direction requests report.' },
        ],
        faqs: [
            { q: 'What is Google My Business and why do I need it?', a: 'Google Business Profile (formerly GMB) is a free listing that shows your business in Google Maps and local search results. It\'s the #1 factor in local SEO — without it, you\'re invisible to customers searching nearby.' },
            { q: 'My business is already on Google — do I still need optimisation?', a: 'A basic, unclaimed listing is very different from a fully optimised profile. Most unclaimed profiles are missing 60–70% of available fields, have no photos and zero reviews — all of which suppress your local ranking.' },
            { q: 'How long before I start ranking higher on Google Maps?', a: 'Initial improvements in local pack ranking typically appear within 30–60 days of full optimisation. Review growth, GMB post activity and citation consistency compound rankings over 3–6 months.' },
            { q: 'Can you manage reviews for multiple business locations?', a: 'Yes — our multi-location package manages any number of profiles. We handle review monitoring, response writing (positive and negative reviews) and monthly reporting across all locations centrally.' },
            { q: 'How do you get more 5-star reviews without it seeming fake?', a: 'We create a systematic ask — WhatsApp messages, email follow-ups and QR code cards — sent to real customers after a genuine positive experience. No fake reviews, no incentivised reviews (which violate Google\'s policy).' },
            { q: 'What happens if my GMB profile gets suspended?', a: 'Profile suspensions are common and can happen due to quality issues or Google updates. We handle reinstatement requests — gathering required documentation and submitting appeals — with a strong track record of reinstatement.' },
            { q: 'Do you post on GMB regularly?', a: 'Yes — weekly Google Posts are included in our management packages. Posts featuring offers, events and updates signal activity to Google\'s algorithm and increase profile engagement from potential customers.' },
            { q: 'Is GMB optimisation different from SEO?', a: 'GMB optimisation (local SEO) and traditional SEO complement each other. Local SEO focuses specifically on map pack and geo-targeted search rankings. We offer both as standalone services or as a combined local growth package.' },
        ],
    },
    {
        slug: 'app-development',
        title: 'App Development',
        iconEmoji: '📲',
        metaDesc: 'Build powerful, scalable iOS and Android mobile apps and progressive web apps that delight users and drive business growth — engineered for performance and built to last.',
        badgeClass: 'badge-cyan',
        badge: 'Mobile & Web Apps',
        tagline: 'Your customers live on their phones. Meet them there with an app that they will actually use.',
        gradientFrom: '#0ea5e9',
        gradientTo: '#0284c7',
        description: `App development is the process of designing, building and deploying mobile applications (iOS and Android) or progressive web applications (PWAs) that solve real user problems and create measurable business value. A great app is not just a mobile version of your website — it is a dedicated experience that leverages smartphone capabilities: push notifications, GPS, camera, offline access and payments to engage users in ways a website cannot. ScalerHouse builds cross-platform mobile apps using React Native and Flutter, delivering a single codebase that runs natively on both iOS and Android — reducing cost without sacrificing performance. From MVP validation to full-scale enterprise applications, we handle the entire lifecycle: UX research, UI design, development, QA, App Store submission and post-launch maintenance.`,
        whyItMatters: [
            { icon: '📱', title: '90% of Mobile Time is In-App', desc: 'Users spend 90% of their mobile time in apps, not browsers. An app gives your brand a permanent home on your customers\' most personal device.' },
            { icon: '🔔', title: 'Push Notifications = Free Re-engagement', desc: 'Push notifications achieve 7–10× higher open rates than email — letting you re-engage customers instantly with offers, updates and reminders at zero incremental cost.' },
            { icon: '💳', title: 'Frictionless Commerce', desc: 'In-app purchases, saved payment methods and one-click ordering convert 3× better than mobile web — dramatically increasing revenue per user.' },
        ],
        howItWorks: [
            { step: '1', title: 'Discovery & Requirements', desc: 'We define the app\'s core user flows, feature scope, technical requirements and platform strategy — iOS only, Android only or cross-platform — based on your audience and budget.' },
            { step: '2', title: 'UX Research & Wireframing', desc: 'We map every user journey with low-fidelity wireframes, validating that the app architecture makes sense before investing in visual design.' },
            { step: '3', title: 'UI Design', desc: 'Our designers create stunning, platform-native interfaces in Figma following Apple\'s HIG and Google\'s Material Design guidelines — tested for usability.' },
            { step: '4', title: 'Development & Integration', desc: 'We build the app in React Native or Flutter, integrating your backend APIs, payment gateways, push notifications, analytics and any third-party services required.' },
            { step: '5', title: 'QA Testing', desc: 'Rigorous testing across 20+ real devices and OS versions — functional, performance, security and UX testing — to ensure a flawless experience before launch.' },
            { step: '6', title: 'App Store Launch & Support', desc: 'We handle App Store and Google Play submission, ASO (App Store Optimisation) for discovery, and provide post-launch bug fix support and ongoing development sprints.' },
        ],
        smallBizBenefits: [
            'Launch a professional app that rivals large-brand experiences on a controlled budget',
            'Engage customers with push notifications, loyalty programmes and in-app offers',
            'MVP (Minimum Viable Product) approach lets you validate before full commitment',
            'Single cross-platform build for iOS and Android — half the cost of two native apps',
        ],
        enterpriseBenefits: [
            'Enterprise-grade security, scalability and infrastructure design for millions of users',
            'Deep backend integration with existing ERP, CRM and database systems',
            'Dedicated development squad with product manager, lead engineers and QA',
            'Ongoing development retainer for continuous feature releases and A/B testing',
        ],
        process: [
            { icon: '🗺️', label: 'Discovery', desc: 'Requirements, platform choice and feature scope definition.' },
            { icon: '📐', label: 'Wireframes', desc: 'User flow mapping and low-fidelity screen architecture.' },
            { icon: '🎨', label: 'UI Design', desc: 'High-fidelity Figma designs with platform-native patterns.' },
            { icon: '👨‍💻', label: 'Development', desc: 'React Native / Flutter build with API and third-party integration.' },
            { icon: '🧪', label: 'QA Testing', desc: 'Rigorous testing across 20+ real devices and OS versions.' },
            { icon: '🚀', label: 'Launch', desc: 'App Store & Play Store submission with ASO and post-launch support.' },
        ],
        faqs: [
            { q: 'Should I build a native app or a cross-platform app?', a: 'For most businesses, React Native or Flutter (cross-platform) delivers 95% of native performance at 50–60% of the cost. We recommend native only when you need deep OS-level hardware access or extreme performance requirements.' },
            { q: 'How long does it take to build a mobile app?', a: 'A simple app with 5–8 screens typically takes 10–14 weeks. A medium-complexity app with backend, payments and social features takes 16–24 weeks. Complex enterprise apps can take 6–12 months.' },
            { q: 'How much does app development cost?', a: 'App cost depends on complexity, features and platforms. Entry-level apps start from ₹5–8 lakh. Mid-range apps with API integrations, payments and push notifications typically cost ₹12–30 lakh. Enterprise apps are scoped custom.' },
            { q: 'Do you handle App Store and Google Play submission?', a: 'Yes — we handle the complete submission process, including developer account setup, screenshots, descriptions, App Store Optimisation (ASO) and responding to any Apple or Google review feedback.' },
            { q: 'Will my app work offline?', a: 'Offline functionality depends on your app\'s requirements. We can build offline-first apps using local storage and sync mechanisms — ideal for field service apps or apps used in low-connectivity environments.' },
            { q: 'Who owns the app code after it\'s built?', a: 'You own 100% of the source code, assets and intellectual property. We provide the complete codebase in a Git repository at project completion — no lock-in.' },
            { q: 'Can you update and maintain the app after launch?', a: 'Yes — we offer monthly maintenance retainers covering OS updates, bug fixes, security patches and feature sprints. Apps require ongoing maintenance as iOS and Android release new OS versions regularly.' },
            { q: 'Can you integrate the app with my existing systems?', a: 'Absolutely. We regularly integrate apps with existing CRMs, ERPs, payment gateways (Razorpay, Stripe), e-commerce platforms, delivery APIs and custom databases via REST or GraphQL APIs.' },
        ],
    },
    {
        slug: 'ui-ux-design',
        title: 'UI/UX Design',
        iconEmoji: '🎨',
        metaDesc: 'Design intuitive, beautiful digital experiences that reduce friction, increase engagement and convert more users — backed by research and validated with real users.',
        badgeClass: 'badge-purple',
        badge: 'User Experience',
        tagline: 'Great design is invisible — users just find your product effortless to use and impossible to leave.',
        gradientFrom: '#8b5cf6',
        gradientTo: '#6d28d9',
        description: `UI (User Interface) design is the visual layer of a digital product — the buttons, typography, colours, layout and visual hierarchy that make it look professional and on-brand. UX (User Experience) design is the strategic layer — the research, information architecture, user flows and interaction patterns that make it intuitive and effortless to use. Done well together, UI/UX design is what makes users say "this just works." ScalerHouse provides full UI/UX design services for websites, mobile apps, SaaS dashboards, e-commerce stores and any digital product. Our design process is rooted in user research — we understand your users' goals and pain points before touching design tools. Every decision is validated through usability testing to ensure the final product performs, not just looks good.`,
        whyItMatters: [
            { icon: '🚀', title: 'Design Drives Conversion', desc: 'A well-designed user interface can increase conversion rates by up to 200%. Every button placement, form field and visual cue either moves users towards conversion or away from it.' },
            { icon: '🧠', title: 'Reduce Cognitive Load', desc: 'Bad UX costs you users silently — they leave without telling you why. Intuitive design reduces confusion, keeps users engaged longer and dramatically lowers churn rates.' },
            { icon: '💰', title: 'ROI of Design', desc: 'Every ₹1 invested in UX returns ₹100 in development savings — fixing UX issues post-build is 100× more expensive than getting them right in the design phase.' },
        ],
        howItWorks: [
            { step: '1', title: 'User Research', desc: 'We conduct interviews, surveys and competitor analysis to understand your users\' goals, behaviours, pain points and mental models before any design begins.' },
            { step: '2', title: 'Information Architecture', desc: 'We structure the content and navigation of your product — sitemaps, user flows and content hierarchy — ensuring users always know where they are and how to get where they want.' },
            { step: '3', title: 'Wireframing', desc: 'Low-fidelity wireframes are created for every key screen, mapping layout and content without the distraction of colour or typography — focused purely on usability.' },
            { step: '4', title: 'UI Design & Design System', desc: 'We create high-fidelity visual designs for all screens — plus a complete design system (colour tokens, typography scale, components library) for consistency at scale.' },
            { step: '5', title: 'Interactive Prototyping', desc: 'Figma prototypes bring the designs to life with interactive transitions — allowing stakeholders and users to experience the product before a line of code is written.' },
            { step: '6', title: 'Usability Testing & Handoff', desc: 'We test prototypes with real users, identify friction points and iterate. Final designs are handed off to developers with detailed specs, assets and a component library.' },
        ],
        smallBizBenefits: [
            'Professional, polished design that makes your brand look as credible as industry leaders',
            'Higher conversion rates through strategic placement of CTAs and trust signals',
            'Faster development — developers have exact specs and no guesswork',
            'User-tested designs that reduce post-launch redesign costs',
        ],
        enterpriseBenefits: [
            'End-to-end design system creation — scalable component libraries across the entire product suite',
            'UX research programmes with qualitative interviews, usability labs and quantitative surveys',
            'Design operations (DesignOps) consulting for large design team coordination',
            'Accessibility audits and WCAG 2.1 AA compliance across all digital touchpoints',
        ],
        process: [
            { icon: '🔍', label: 'Research', desc: 'User interviews, surveys and competitor benchmarking.' },
            { icon: '🗺️', label: 'Architecture', desc: 'Sitemaps, user flows and content hierarchy mapping.' },
            { icon: '📐', label: 'Wireframes', desc: 'Low-fidelity layouts defining structure before aesthetics.' },
            { icon: '🖼️', label: 'UI Design', desc: 'High-fidelity designs plus a full design system.' },
            { icon: '🖱️', label: 'Prototype', desc: 'Interactive Figma prototypes for stakeholder and user testing.' },
            { icon: '📦', label: 'Handoff', desc: 'Developer-ready specs, assets, annotations and component library.' },
        ],
        faqs: [
            { q: 'What is the difference between UI and UX design?', a: 'UX (User Experience) design focuses on how a product works — the research, user flows and information architecture. UI (User Interface) design focuses on how it looks — visual design, colours, typography and components. Great digital products need both working together.' },
            { q: 'Do you conduct user research or just create visual designs?', a: 'We conduct full UX research — user interviews, usability testing, card sorting and competitor audits. This research informs every design decision and significantly increases the probability that the final product solves real user problems.' },
            { q: 'What tools do you use for UI/UX design?', a: 'We primarily use Figma for all design and prototyping work. We also use Hotjar and Maze for user testing, Miro for collaborative UX workshops and ZeroHeight for publishing design systems.' },
            { q: 'Do you create mobile app designs or just websites?', a: 'Both. We design for all digital platforms — websites, iOS and Android mobile apps, SaaS dashboards, e-commerce stores, admin panels and any custom digital product.' },
            { q: 'What is a design system and do I need one?', a: 'A design system is a library of reusable components, colours, typography and patterns that ensures visual consistency across your entire product. It\'s essential for any product with a growing team or multiple digital touchpoints.' },
            { q: 'Can you redesign my existing app or website?', a: 'Yes — redesigns are a large part of our work. We begin with a UX audit of your existing product, identifying usability issues and conversion blockers before creating the new design.' },
            { q: 'Will the design be handed off to developers properly?', a: 'Yes — developer handoff is a dedicated phase. We provide annotated Figma files with spacing, component states, interaction specs and exported assets so developers can build pixel-perfectly without guessing.' },
            { q: 'How many design revisions are included?', a: 'Our standard engagement includes two rounds of revisions at each design stage (wireframes and high-fidelity UI). Additional revisions are available at a fixed hourly rate, or you can purchase an extended revision package.' },
        ],
    },
    {
        slug: 'graphic-designing',
        title: 'Graphic Designing',
        iconEmoji: '🖌️',
        metaDesc: 'Elevate your brand with professional graphic design — marketing materials, social media creatives, presentations, packaging and everything in between that makes your brand visually unforgettable.',
        badgeClass: 'badge-pink',
        badge: 'Visual Identity',
        tagline: 'Visuals that stop the scroll, tell your story and make your brand impossible to ignore.',
        gradientFrom: '#f43f5e',
        gradientTo: '#e11d48',
        description: `Graphic design is the art and practice of creating visual content — using typography, colour, imagery and layout to communicate ideas and messages to an audience. In business, every visual touchpoint either builds or erodes brand perception: your social media posts, brochures, packaging, email banners, presentation decks and offline ads all tell someone what kind of brand you are before they read a single word. ScalerHouse provides comprehensive graphic design services for businesses of all sizes — from startups building a brand identity for the first time to established companies needing consistent, high-volume design output. Our designers combine aesthetic sensibility with strategic thinking: every piece is designed not just to look great but to serve a specific communication or conversion goal.`,
        whyItMatters: [
            { icon: '👁️', title: 'Visual First Impressions', desc: 'People process visuals 60,000× faster than text. Professional design creates an immediate emotional response — trust, excitement, desire — before a potential customer reads your headline.' },
            { icon: '🔄', title: 'Brand Consistency = Trust', desc: 'Consistent visual branding across all touchpoints increases brand recognition by 80% and builds the repetitive familiarity that converts strangers into loyal customers.' },
            { icon: '📣', title: 'Design Drives Engagement', desc: 'Social media posts with professional visuals receive 94% more views than text-only posts. Great design is not a luxury — it\'s the difference between being noticed and being ignored.' },
        ],
        howItWorks: [
            { step: '1', title: 'Brand Brief & Style Discovery', desc: 'We begin by understanding your brand identity, values, target audience and the message each piece needs to communicate — ensuring design decisions are strategic.' },
            { step: '2', title: 'Competitor & Inspiration Research', desc: 'We analyse what leading brands in your category are doing visually and identify differentiation opportunities to ensure your design stands out rather than blends in.' },
            { step: '3', title: 'Concept Development', desc: 'Our designers develop 2–3 distinct initial concepts for key deliverables, each exploring different visual directions — giving you creative options to choose from.' },
            { step: '4', title: 'Design Refinement', desc: 'Based on your feedback, we refine the chosen concept — perfecting typography, colour balance, layout and visual hierarchy until the design is exactly right.' },
            { step: '5', title: 'Quality Review & Brand Check', desc: 'Every finished piece goes through a quality review — checking technical specs, colour accuracy and brand consistency before anything is delivered to you.' },
            { step: '6', title: 'Delivery & File Handoff', desc: 'We deliver all files in the formats you need: print-ready PDFs, web-optimised PNGs/JPEGs, social media sizes and editable source files (Adobe or Figma).' },
        ],
        smallBizBenefits: [
            'Professional-looking marketing materials that compete with established brands',
            'Consistent visual identity across social media, print and digital channels',
            'Fast turnaround on high-volume design needs — posts, banners and brochures',
            'Editable templates delivered so you can create new content independently',
        ],
        enterpriseBenefits: [
            'Dedicated design team on a monthly retainer for unlimited design volume',
            'Brand guideline enforcement across all outputs and design team members',
            'Large-format and outdoor advertising design (hoardings, vehicle wraps, exhibitions)',
            'Annual report, pitch deck and investor presentation design at boardroom level',
        ],
        process: [
            { icon: '📋', label: 'Brief', desc: 'Understanding brand, audience, goal and message for each piece.' },
            { icon: '🔍', label: 'Research', desc: 'Competitor visual audit and inspiration benchmarking.' },
            { icon: '💡', label: 'Concepts', desc: '2–3 distinct creative directions presented for review.' },
            { icon: '✏️', label: 'Refine', desc: 'Revisions on chosen concept — typography, colour and layout.' },
            { icon: '✅', label: 'Review', desc: 'Brand consistency and technical spec quality check.' },
            { icon: '📦', label: 'Deliver', desc: 'All formats — print, web, social and editable source files.' },
        ],
        faqs: [
            { q: 'What types of graphic design do you offer?', a: 'We cover all categories: social media creatives, marketing brochures, flyers, presentations, packaging design, email banners, website banners, print ads, exhibition materials, infographics, menus and more.' },
            { q: 'How many revisions are included?', a: 'Our standard packages include 2 rounds of revisions per deliverable. Additional revisions are available at a flat rate. We find 2 rounds is sufficient for 90% of projects with a clear brief.' },
            { q: 'What file formats will I receive?', a: 'You receive all formats relevant to your use case: print-ready PDF (CMYK, 300 DPI), web-optimised PNG and JPEG, animated GIF or MP4 for digital ads, and editable source files in Adobe Illustrator, Photoshop or Figma.' },
            { q: 'Do you follow my brand guidelines?', a: 'Absolutely — brand consistency is a priority. Provide us with your brand guideline document and we strictly follow colour codes, typography, logo usage rules and brand tone in every piece.' },
            { q: 'What if I don\'t have brand guidelines yet?', a: 'We can develop a basic brand kit for you — covering logo, primary and secondary colours, typography and usage guidelines — before beginning any design work. Ask about our brand identity package.' },
            { q: 'How fast can you turn around designs?', a: 'Standard turnaround is 2–3 business days for simple graphics (social posts, banners). Complex multi-page documents or full-campaign design sets typically take 5–7 business days.' },
            { q: 'Can I get a monthly retainer for ongoing design needs?', a: 'Yes — our design retainer is ideal for businesses with ongoing needs (social posts, email banners, ads). You get a fixed number of design credits per month at a predictable monthly cost.' },
            { q: 'Do you design for print as well as digital?', a: 'Yes — we design for both. Print files are supplied CMYK, at 300 DPI, with bleed and crop marks as required by your printer. We can also liaise directly with your printer to ensure accurate colour reproduction.' },
        ],
    },
    {
        slug: 'logo-designing',
        title: 'Logo Designing',
        iconEmoji: '✏️',
        metaDesc: 'Get a distinctive, timeless logo that captures your brand\'s personality and looks exceptional across every medium — from business cards to billboards.',
        badgeClass: 'badge-yellow',
        badge: 'Brand Identity',
        tagline: 'Your logo is the face of your brand — make it one that people remember, recognise and trust.',
        gradientFrom: '#eab308',
        gradientTo: '#ca8a04',
        description: `A logo is the single most recognisable visual element of a brand. It appears on your website, business cards, packaging, uniforms, signage, social media and everywhere your brand meets the world. A great logo is not just a pretty image — it is a strategic distillation of your brand's personality, values and positioning into a mark that communicates instantly, works at every size and stands the test of time. ScalerHouse's logo design process is research-driven and strategic: we study your industry, target audience and competitive landscape before a single concept is sketched. We then develop multiple unique logo directions, each rooted in a clear brand rationale, and refine the chosen direction until you have a logo that truly represents who you are.`,
        whyItMatters: [
            { icon: '🆔', title: 'Instant Brand Recognition', desc: 'A distinctive logo makes your brand immediately recognisable across all touchpoints — from a 5cm business card to a 5-metre hoarding without losing impact.' },
            { icon: '🎯', title: 'Communicates Without Words', desc: 'The right logo shape, colour and typography communicate your brand\'s personality — premium, playful, trustworthy, innovative — before a prospect reads your tagline.' },
            { icon: '🏛️', title: 'The Foundation of All Design', desc: 'Your logo sets the visual tone for every other design element: brand colours, typography, photography style and graphic patterns all follow from the logo.' },
        ],
        howItWorks: [
            { step: '1', title: 'Brand Discovery Session', desc: 'We explore your brand values, target audience, personality, competitors and visual preferences through a structured discovery questionnaire and briefing call.' },
            { step: '2', title: 'Research & Conceptualisation', desc: 'We research your industry\'s visual language, identify differentiation opportunities and sketch multiple conceptual directions — wordmarks, lettermarks, emblems, monograms and combination marks.' },
            { step: '3', title: 'Initial Logo Concepts', desc: 'We present 3 distinct logo concepts with rationale — explaining why each direction communicates your brand. Concepts are shown in black and white first to validate form before colour.' },
            { step: '4', title: 'Refinement & Colour Exploration', desc: 'We refine your chosen concept — iterating on proportions, letterforms and spacing — then present primary and secondary colour palette options with psychological rationale.' },
            { step: '5', title: 'Brand Mark Variations', desc: 'The final logo is developed in all necessary variations: horizontal, stacked, icon-only and monochrome — ensuring it works in every usage scenario.' },
            { step: '6', title: 'File Delivery & Brand Guide', desc: 'We deliver a complete logo package: all file formats (SVG, AI, EPS, PNG, PDF) in colour, reversed and mono, plus a one-page mini brand guide covering logo usage, colours and typography.' },
        ],
        smallBizBenefits: [
            'Professional logo that instantly communicates credibility to first-time prospects',
            'All file formats delivered so the logo works everywhere — print, digital, embroidery',
            'Mini brand guide included to ensure consistent logo usage going forward',
            'Standalone investment that serves your brand for 10+ years',
        ],
        enterpriseBenefits: [
            'Full brand identity system — logo suite, colour system, typography, iconography and patterns',
            'Brand strategy pre-work — positioning, personality and visual territory definition',
            'Brand refresh — evolving an existing logo while preserving brand equity',
            'Usage guidelines comprehensive enough for global agencies and large design teams',
        ],
        process: [
            { icon: '💬', label: 'Discovery', desc: 'Brand values, audience, competitors and visual preference briefing.' },
            { icon: '🔬', label: 'Research', desc: 'Industry visual audit and conceptual direction exploration.' },
            { icon: '✏️', label: 'Concepts', desc: '3 distinct logo directions presented with strategic rationale.' },
            { icon: '🎨', label: 'Refine', desc: 'Refinement of chosen concept with colour palette exploration.' },
            { icon: '📐', label: 'Variations', desc: 'Full logo suite — horizontal, stacked, icon, mono and reverse.' },
            { icon: '📦', label: 'Deliver', desc: 'Complete file package in all formats plus mini brand guide.' },
        ],
        faqs: [
            { q: 'How many logo concepts will I receive?', a: 'We present 3 distinct, fully developed logo concepts. After you select your preferred direction, we refine it through 2 rounds of revisions until it is exactly right — plus deliver all variations and formats.' },
            { q: 'Will I own the logo completely?', a: 'Yes — upon final payment, all intellectual property rights for the logo transfer entirely to you. You receive full ownership of all working files, vector formats and rights to use the logo however you wish.' },
            { q: 'What file formats will I receive?', a: 'You receive: SVG (scalable for any size), AI/EPS (editable source files), PNG (transparent background, multiple sizes) and PDF — in colour, black and white and reversed (white) versions.' },
            { q: 'How long does the logo design process take?', a: 'The full logo design process — from brief to final delivery — typically takes 10–14 business days. Rush timelines (5–7 business days) are available at an additional cost.' },
            { q: 'What if I don\'t like any of the 3 concepts?', a: 'This is rare when our brief is thorough, but if a new creative direction is needed, we will create one additional concept set. We are committed to delivering a logo you love and are confident in.' },
            { q: 'Can you redesign my existing logo?', a: 'Yes — logo refreshes are common. We can modernise your existing logo while preserving the brand equity and recognition you have already built, or create a completely new identity if a full rebrand is the goal.' },
            { q: 'Do you design the full brand identity or just the logo?', a: 'Logo design is available as a standalone service. We also offer full brand identity packages that include logo, colour system, typography, brand patterns, iconography and comprehensive brand guidelines.' },
            { q: 'What information do I need to provide?', a: 'We need: your business name, industry, target audience, competitor logos (for reference), any businesses whose visual identity you admire, your preferred style (modern, classic, playful, premium) and preferred colours if any.' },
        ],
    },
    {
        slug: 'crm-development',
        title: 'CRM Development',
        iconEmoji: '🗃️',
        metaDesc: 'Build a custom CRM system tailored to your exact sales process — track leads, manage pipelines, automate follow-ups and never let a business opportunity slip through the cracks.',
        badgeClass: 'badge-green',
        badge: 'Sales Automation',
        tagline: 'Stop managing relationships in spreadsheets. Your sales pipeline deserves a system built for how you actually work.',
        gradientFrom: '#10b981',
        gradientTo: '#059669',
        description: `A CRM (Customer Relationship Management) system is software that centralises all your customer data, sales interactions, deal stages and follow-up activities in one place — giving your entire team visibility into every relationship and ensuring no lead is ever forgotten. While off-the-shelf CRMs like Salesforce or HubSpot work for many businesses, they often don't fit the unique sales workflows, custom fields or specific integrations that a growing business needs. ScalerHouse builds bespoke CRM systems from scratch — or heavily customises existing platforms — so the technology fits your business process rather than forcing your business to adapt to the technology. The result is higher adoption, better data quality and a sales pipeline that is actually managed rather than merely tracked.`,
        whyItMatters: [
            { icon: '💼', title: 'Never Lose a Lead', desc: 'The average business loses 79% of leads due to lack of follow-up. A CRM with automated reminders and pipeline stages ensures every opportunity is nurtured until it closes or is disqualified.' },
            { icon: '📊', title: 'Full Sales Visibility', desc: 'See every deal\'s stage, value and next action at a glance. Accurate pipeline data lets you forecast revenue, identify bottlenecks and make confident business decisions.' },
            { icon: '⚙️', title: 'Automate Repetitive Tasks', desc: 'Automatic follow-up emails, task creation, lead assignment and status updates eliminate hours of manual admin — so your sales team focuses on selling, not data entry.' },
        ],
        howItWorks: [
            { step: '1', title: 'Sales Process Mapping', desc: 'We document your end-to-end sales process — from lead source to closed-won — mapping every stage, touchpoint, handoff and data point that matters to your team.' },
            { step: '2', title: 'CRM Architecture Design', desc: 'We design the data structure: entities (contacts, companies, deals, activities), custom fields, pipeline stages, user roles and permissions — tailored to your exact workflow.' },
            { step: '3', title: 'Development & Customisation', desc: 'We build the CRM — either custom-coded on a modern tech stack or by deeply customising an existing platform. Core modules: pipeline, contact management, task management, email and reporting.' },
            { step: '4', title: 'Integration', desc: 'We integrate the CRM with your existing tools: website lead forms, WhatsApp, email clients, marketing platforms, payment gateways and ERP systems.' },
            { step: '5', title: 'Automation Setup', desc: 'We configure automations — lead assignment rules, follow-up email sequences, stage-change triggers and reporting alerts — reducing manual work for your team.' },
            { step: '6', title: 'Training & Onboarding', desc: 'We train your sales team on the CRM with guided sessions and documentation — ensuring high adoption from day one, followed by 30-day post-go-live support.' },
        ],
        smallBizBenefits: [
            'Replace scattered spreadsheets with a single, organised system for all leads and customers',
            'Automated follow-up reminders so no lead ever falls through the cracks',
            'Simple, intuitive interface your whole team will actually use',
            'WhatsApp and email integration to manage all communication from one place',
        ],
        enterpriseBenefits: [
            'Custom CRM built for complex multi-stage B2B enterprise sales cycles',
            'Role-based access — individual contributor, team lead, manager and admin views',
            'Advanced reporting: pipeline analytics, win/loss analysis and rep performance dashboards',
            'ERP, SAP, Tally and third-party system integration via secure REST APIs',
        ],
        process: [
            { icon: '🗺️', label: 'Process Map', desc: 'Document your complete sales workflow and data requirements.' },
            { icon: '🏗️', label: 'Architecture', desc: 'Design entities, fields, stages and user roles.' },
            { icon: '👨‍💻', label: 'Build', desc: 'CRM development and customisation with all core modules.' },
            { icon: '🔌', label: 'Integrate', desc: 'Connect website, email, WhatsApp, marketing tools and ERPs.' },
            { icon: '⚙️', label: 'Automate', desc: 'Lead assignment, follow-up sequences and workflow triggers.' },
            { icon: '🎓', label: 'Train', desc: 'Team training, documentation and 30-day post-launch support.' },
        ],
        faqs: [
            { q: 'Do you build custom CRMs or configure existing platforms like HubSpot?', a: 'Both. We evaluate your needs to recommend the best path — HubSpot, Salesforce or Zoho CRM customisation is faster and lower cost for most businesses. Custom-built CRMs are recommended when existing platforms don\'t fit your workflow.' },
            { q: 'What is the difference between a custom CRM and an off-the-shelf CRM?', a: 'Off-the-shelf CRMs (HubSpot, Salesforce) are generalised tools you adapt to your process. A custom CRM is purpose-built for your exact sales workflow, fields and integrations — with no unnecessary features and no monthly licensing fees.' },
            { q: 'Can the CRM integrate with WhatsApp for lead management?', a: 'Yes — we integrate WhatsApp Business API into CRM systems, allowing your team to send and receive WhatsApp messages, log conversations and trigger automated WhatsApp follow-ups from within the CRM.' },
            { q: 'How long does CRM development take?', a: 'A CRM customisation (HubSpot/Zoho) typically takes 4–8 weeks. A fully custom-built CRM system takes 12–20 weeks depending on feature complexity and the number of integrations required.' },
            { q: 'Will it work on mobile for our field sales team?', a: 'Yes — all CRMs we build are mobile-responsive web applications. For field-heavy teams, we can also build a dedicated iOS/Android app as part of the CRM project.' },
            { q: 'Can you migrate our existing data from spreadsheets into the new CRM?', a: 'Absolutely — data migration is a standard part of our CRM implementation. We clean, structure and import your historical contacts, companies and deal data into the new system.' },
            { q: 'What reporting will the CRM provide?', a: 'Standard reporting includes: pipeline value by stage, lead source performance, sales rep activity, deal velocity, win rate and monthly revenue forecasts. Custom reports are built to match your specific KPIs.' },
            { q: 'Can the CRM handle support tickets as well as sales?', a: 'Yes — we can build combined Sales CRM + Helpdesk functionality, or integrate the sales CRM with a dedicated helpdesk tool (Freshdesk, Zendesk) for businesses that need both workflows managed together.' },
        ],
    },
    {
        slug: 'api-automations',
        title: 'API & Automations',
        iconEmoji: '⚡',
        metaDesc: 'Connect your tools, eliminate manual work and scale operations without scaling headcount — through custom API integrations and intelligent business process automation.',
        badgeClass: 'badge-orange',
        badge: 'Workflow Automation',
        tagline: 'Stop copy-pasting between apps. Automate your repetitive workflows and let your team focus on work that actually matters.',
        gradientFrom: '#f59e0b',
        gradientTo: '#d97706',
        description: `APIs (Application Programming Interfaces) are the connective tissue of the modern digital business — they allow different software systems to talk to each other and share data in real time. Business process automation uses these connections — combined with logic, triggers and conditions — to replace repetitive manual tasks with automated workflows that run themselves. ScalerHouse's API and Automations service designs, builds and maintains custom integrations and automation workflows for businesses of all sizes. Whether you need your CRM to automatically create WhatsApp messages when a new lead arrives, your e-commerce orders to sync to your ERP system in real time, or 20 hours of monthly manual data entry to be eliminated — we identify the bottlenecks, design the solution and build it. The result is a leaner operation that scales without proportional headcount growth.`,
        whyItMatters: [
            { icon: '⏰', title: 'Reclaim Hours Every Week', desc: 'The average knowledge worker spends 19% of their time searching for information and 16% on manual, repetitive data tasks. Automation reclaims these hours for high-value work.' },
            { icon: '🎯', title: 'Eliminate Human Error', desc: 'Manual data entry between systems introduces errors that cause billing mistakes, missed follow-ups and bad customer experiences. Automation executes perfectly every time.' },
            { icon: '📈', title: 'Scale Without Proportional Cost', desc: 'Automation allows you to handle 10× the volume of orders, leads or support tickets at the same operational cost — making growth profitable rather than just busy.' },
        ],
        howItWorks: [
            { step: '1', title: 'Workflow Discovery & Audit', desc: 'We map your current manual workflows — interviews with your team, observation of existing processes and identification of the highest-value automation opportunities.' },
            { step: '2', title: 'Solution Design', desc: 'We design the automation architecture — triggers, conditions, data transformations, error handling and fallback logic — documented in a clear workflow diagram before any building begins.' },
            { step: '3', title: 'API Integration', desc: 'We build secure API connections between your systems (CRM, ERP, WhatsApp, payment gateways, email tools, databases) using REST/GraphQL APIs and webhooks.' },
            { step: '4', title: 'Automation Build', desc: 'We build the automation workflows using tools like Zapier, Make (Integromat), n8n or custom Node.js scripts for complex logic that off-the-shelf automation tools cannot handle.' },
            { step: '5', title: 'Testing & Error Handling', desc: 'Every automation is tested with real data across success and failure scenarios — with clear error logging, retry logic and alerts set up so you know immediately if something fails.' },
            { step: '6', title: 'Deployment, Documentation & Monitoring', desc: 'Automations go live with full documentation of every workflow — triggers, actions, data fields and error states — plus optional ongoing monitoring and maintenance retainer.' },
        ],
        smallBizBenefits: [
            'Eliminate hours of weekly manual data entry between systems',
            'Automatic WhatsApp, email or SMS follow-ups the moment a lead arrives',
            'No-code automation tools (Zapier/Make) when suitable — lower cost, faster delivery',
            'Connect your website, CRM, accounting and communication tools into one system',
        ],
        enterpriseBenefits: [
            'Custom-coded automation pipelines for complex, high-volume business logic',
            'Enterprise API gateway management — rate limiting, authentication, monitoring',
            'Event-driven architectures with message queues (RabbitMQ, Kafka) for scale',
            'iPaaS platform management — MuleSoft, Boomi, Azure Logic Apps for enterprise integration',
        ],
        process: [
            { icon: '🗺️', label: 'Discovery', desc: 'Map manual workflows and identify highest-ROI automation opportunities.' },
            { icon: '📐', label: 'Design', desc: 'Automation architecture — triggers, logic, error handling and data flow maps.' },
            { icon: '🔌', label: 'API Connect', desc: 'Secure API integrations between all systems using REST/webhooks.' },
            { icon: '⚙️', label: 'Build', desc: 'Automation workflows via Zapier, Make, n8n or custom code.' },
            { icon: '🧪', label: 'Test', desc: 'Full testing with real data, error scenarios and retry logic validation.' },
            { icon: '🚀', label: 'Deploy', desc: 'Live deployment with documentation, monitoring and support.' },
        ],
        faqs: [
            { q: 'What is an API integration?', a: 'An API integration connects two software applications so they can share data automatically. For example: when a lead fills a form on your website, an API integration can instantly create a contact in your CRM, send a WhatsApp message and add the lead to an email sequence — all without manual work.' },
            { q: 'What tools can you integrate?', a: 'We integrate virtually any system that has an API: CRMs (HubSpot, Salesforce, Zoho), ERPs (SAP, Tally, Microsoft Dynamics), e-commerce (Shopify, WooCommerce), communication (WhatsApp Business API, Twilio, Mailchimp), payments (Razorpay, Stripe) and custom databases.' },
            { q: 'Do you use no-code tools or write custom code?', a: 'Both, depending on complexity and volume. For straightforward integrations, no-code tools like Zapier or Make are faster and lower cost. For complex business logic, high-volume processing or custom transformations, we write custom Node.js or Python scripts.' },
            { q: 'What is a webhook and how does it differ from an API?', a: 'An API is a request/response system — you ask for data and receive it. A webhook is event-driven — a system automatically sends data to you the moment an event occurs. Webhooks are used for real-time triggers like "new order placed" or "payment received."' },
            { q: 'How do you ensure automations don\'t fail silently?', a: 'Every automation we build includes error logging, retry logic for transient failures and alert notifications (email or Slack) when an automation fails. We also set up a monitoring dashboard so you can see automation health at a glance.' },
            { q: 'Can you automate our WhatsApp follow-up messages?', a: 'Yes — using the official WhatsApp Business API (via providers like Wati, Aisensy or Twilio), we can automate personalised WhatsApp messages triggered by specific events: new lead, purchase confirmation, appointment reminder or re-engagement.' },
            { q: 'Will automation break if one of my tools updates?', a: 'API changes by third-party providers can break integrations — this is a real risk with any automation. Our optional maintenance retainer includes monitoring for API changes and updating integrations proactively to prevent downtime.' },
            { q: 'How do you calculate the ROI of automation?', a: 'We calculate automation ROI by measuring the time saved per week × hourly staff cost + error reduction value + speed-to-lead improvement. Most automation projects deliver full ROI within 3–6 months of implementation.' },
        ],
    },
];
